---
- hosts: all
  tasks:
    - name: "Create local directories"
      file:
        path: "{{ homedir }}/{{ item }}"
        state: directory
        mode: 0755
      loop:
        - .gitolite/logs
        - .ssh
        - local/src
        - local/bin
    - name: "Setup .bashrc"
      lineinfile:
        path: "{{ homedir }}/.bashrc"
        line: "{{ item }}"
      loop:
        - 'export PATH=$HOME/local/bin:$PATH'
        - 'export CPPFLAGS=-I$HOME/local/include'
        - 'export LDFLAGS="-L$HOME/local/lib -Wl,-rpath -Wl,$HOME/local/lib"'
        - 'export PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"'
        - 'export MANPATH=$HOME/local/man:$HOME/local/share/man:$MANPATH'
    - name: "Download and extract gitolite release"
      unarchive:
        src: https://github.com/sitaramc/gitolite/archive/v3.6.11.tar.gz
        remote_src: yes
        dest: "{{ homedir }}/local/src"
        creates: "{{ homedir }}/local/src/gitolite-3.6.11/README.markdown"
    - name: "Install gitolite"
      command: ./install -ln "{{ homedir }}/local/bin" chdir="{{ homedir }}/local/src/gitolite-3.6.11" creates="{{ homedir }}/local/bin/gitolite"
    - name: "Copy public key"
      copy:
        src: /home/wroberts/.ssh/gitolite_rsa.pub
        dest: "{{ homedir }}/.ssh/gitolite_rsa.pub"
    - name: "Setup gitolite"
      command: local/bin/gitolite setup -pk {{ homedir }}/.ssh/gitolite_rsa.pub
